services:
  grafana:
    user: root
    container_name: 'idx-predefinedintervalbuttons-panel'

    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.4.0}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/idx-predefinedintervalbuttons-panel
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/idx-predefinedintervalbuttons-panel

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.idx-predefinedintervalbuttons-panel:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: idx-predefinedintervalbuttons-panel
